# fly -t concourse set-pipeline --config './concourse.yaml' --pipeline 'docker-draw.io' --load-vars-from ./concourse.vars
resources:
  - name: version
    type: semver
    icon: git
    source:
      driver: git
      uri: https://github.com/fjudith/docker-alfresco.git
      branch: master
      file: VERSION
  
  - name: docker-alfresco
    type: git
    icon: git
    source:
      uri: https://github.com/fjudith/docker-alfresco.git
      branch: master
  
  - name: repository
    type: registry-image
    icon: docker 
    source:
      username: ((registry-username))
      password: ((registry-password))
      repository: ((registry-repo))/alfresco-repository
      tag: latest

  - name: share
    type: registry-image
    icon: docker 
    source:
      username: ((registry-username))
      password: ((registry-password))
      repository: ((registry-repo))/alfresco-share
      tag: latest

  - name: libreoffice
    type: registry-image
    icon: docker 
    source:
      username: ((registry-username))
      password: ((registry-password))
      repository: ((registry-repo))/alfresco-libreoffice
      tag: latest

  - name: search
    type: registry-image
    icon: docker 
    source:
      username: ((registry-username))
      password: ((registry-password))
      repository: ((registry-repo))/alfresco-search
      tag: latest
  
  - name: object-storage
    type: s3
    icon: folder-network
    source:
      endpoint: ((s3-endpoint))
      bucket: ((s3-bucket))
      access_key_id: ((s3-access-key))
      secret_access_key: ((s3-secret-key))
      disable_ssl: true
      path: docker-alfresco
      regexp: (.*)_version


jobs:
  - name: write-repository-tags
    public: true
    plan:
      - get: version
        trigger: true
      - task: write-additional-tags
        config:
          platform: linux
          image_resource:
            type: registry-image
            source: { repository: busybox }
          inputs:
              - name: version
          run:
            path: sh
            args:
              - -ec
              - |
                echo "$(cat version/version)-repository" | tee additionnal_tags/repository_version
          outputs:
            - name: additionnal_tags
      - put: object-storage
        params:
          file: "additionnal_tags/*"

  - name: write-share-tags
    public: true
    plan:
      - get: version
        trigger: true
      - task: write-additional-tags
        config:
          platform: linux
          image_resource:
            type: registry-image
            source: { repository: busybox }
          inputs:
              - name: version
          run:
            path: sh
            args:
              - -ec
              - |
                echo "$(cat version/version)-share" | tee additionnal_tags/share_version
          outputs:
            - name: additionnal_tags
      - put: object-storage
        params:
          file: "additionnal_tags/*"

  - name: write-search-tags
    public: true
    plan:
      - get: version
        trigger: true
      - task: write-additional-tags
        config:
          platform: linux
          image_resource:
            type: registry-image
            source: { repository: busybox }
          inputs:
              - name: version
          run:
            path: sh
            args:
              - -ec
              - |
                echo "$(cat version/version)-search" | tee additionnal_tags/search_version
          outputs:
            - name: additionnal_tags
      - put: object-storage
        params:
          file: "additionnal_tags/*"

  - name: write-libreoffice-tags
    public: true
    plan:
      - get: version
        trigger: true
      - task: write-additional-tags
        config:
          platform: linux
          image_resource:
            type: registry-image
            source: { repository: busybox }
          inputs:
              - name: version
          run:
            path: sh
            args:
              - -ec
              - |
                echo "$(cat version/version)-libreoffice" | tee additionnal_tags/libreoffice_version
          outputs:
            - name: additionnal_tags
      - put: object-storage
        params:
          file: "additionnal_tags/*"

  - name: build-repository
    public: true
    plan:
    - get: docker-alfresco
    - get: object-storage
      passed: [write-repository-tags]
      trigger: true
    - task: build
      privileged: true
      config:
        platform: linux
        image_resource:
          type: registry-image
          source:
            repository: vito/oci-build-task
        params:
          CONTEXT: ./docker-alfresco/repository/
          DOCKERFILE: ./docker-alfresco/repository/Dockerfile
        inputs:
          - name: docker-alfresco
        outputs:
          - name: image
        run:
          path: build
    - put: repository
      params: {image: image/image.tar, additional_tags: ./object-storage/repository_version}

  - name: build-share
    public: true
    plan:
    - get: docker-alfresco
    - get: object-storage
      passed: [write-share-tags]
      trigger: true
    - task: build
      privileged: true
      config:
        platform: linux
        image_resource:
          type: registry-image
          source:
            repository: vito/oci-build-task
        params:
          CONTEXT: ./docker-alfresco/share/
          DOCKERFILE: ./docker-alfresco/share/Dockerfile
        inputs:
          - name: docker-alfresco
        outputs:
          - name: image
        run:
          path: build
    - put: share
      params: {image: image/image.tar, additional_tags: ./object-storage/share_version}

  - name: build-search
    public: true
    plan:
    - get: docker-alfresco
    - get: object-storage
      passed: [write-search-tags]
      trigger: true
    - task: build
      privileged: true
      config:
        platform: linux
        image_resource:
          type: registry-image
          source:
            repository: vito/oci-build-task
        params:
          CONTEXT: ./docker-alfresco/search/
          DOCKERFILE: ./docker-alfresco/search/Dockerfile
        inputs:
          - name: docker-alfresco
        outputs:
          - name: image
        run:
          path: build
    - put: search
      params: {image: image/image.tar, additional_tags: ./object-storage/search_version}

  - name: build-libreoffice
    public: true
    plan:
    - get: docker-alfresco
    - get: object-storage
      passed: [write-libreoffice-tags]
      trigger: true
    - task: build
      privileged: true
      config:
        platform: linux
        image_resource:
          type: registry-image
          source:
            repository: vito/oci-build-task
        params:
          CONTEXT: ./docker-alfresco/libreoffice/
          DOCKERFILE: ./docker-alfresco/libreoffice/Dockerfile
        inputs:
          - name: docker-alfresco
        outputs:
          - name: image
        run:
          path: build
    - put: libreoffice
      params: {image: image/image.tar, additional_tags: ./object-storage/libreoffice_version}
