version: '2'
volumes:
  alfresco-db:
  alfresco-search-cores-alfresco:
  alfresco-search-cores-archive:
  alfresco-search-contentstore:
  alfresco-data:
  alfresco-logs:

services:
  postgresql:
    environment:
      POSTGRES_DB: alfresco
      POSTGRES_PASSWORD: alfresco
      POSTGRES_USER: alfresco
    image: postgres:9.4
    volumes:
      - alfresco-db:/var/lib/postgresql/data
  
  libreoffice:
    build: libreoffice/
    image: fjudith/alfresco:libreoffice
    ports:
      - "8100:8100"
  
  search:
    build: search/
    image: fjudith/alfresco:search
    ports:
      - "8983:8983"
    volumes:
      - alfresco-search-cores-alfresco:/usr/share/alfresco-search-services/solrhome/alfresco
      - alfresco-search-cores-archive:/usr/share/alfresco-search-services/solrhome/archive
      - alfresco-search-contentstore:/usr/share/alfresco-search-services/contentstore
  
  repository:
    environment:
      DB_HOST: postgres
      DB_KIND: postgresql
      DB_NAME: alfresco
      DB_PASSWORD: alfresco
      DB_USERNAME: alfresco
      #LDAP_AUTH_USERNAMEFORMAT: uid=%s,cn=users,cn=accounts,dc=example,dc=com
      #LDAP_DEFAULT_ADMINS: admin
      #LDAP_ENABLED: true
      #LDAP_GROUP_SEARCHBASE: cn=groups,cn=accounts,dc=example,dc=com
      #LDAP_SECURITY_CREDENTIALS: secret
      #LDAP_SECURITY_PRINCIPAL: uid=admin,cn=users,cn=accounts,dc=example,dc=com
      #LDAP_URL: ldap://ipa.example.com:389
      #LDAP_USER_SEARCHBASE: cn=users,cn=accounts,dc=example,dc=com
    build: repository/
    image: fjudith/alfresco:repository
    links:
      - postgresql:postgres
      - libreoffice:libreoffice
      - search:solr
    ports:
      - "21:21"
      - "137:137"
      - "138:138"
      - "139:139"
      - "445:445"
      - "8009:8009"
    volumes:
    volumes:
      - alfresco-data:/var/lib/alfresco/alf_data
      - alfresco-logs:/usr/share/tomcat/logs
  
  share:
    build: share/
    image: fjudith/alfresco:share
    ports:
      - "8080:8080"
    links:
      - repository:repository