apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: alfresco-log
  namespace: alfresco
  labels:
    app: alfresco
    tiers: demo
spec:
  # storageClassName: ''
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: alfresco-data
  namespace: alfresco
  labels:
    app: alfresco
    tiers: demo
spec:
  # storageClassName: ''
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
