apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gateway
  namespace: alfresco
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - http:
      paths:
      - path: /share
        backend:
          serviceName: share
          servicePort: 8080
      - path: /alfresco
        backend:
          serviceName: repository
          servicePort: 8080