apiVersion: apps/v1
kind: Deployment
metadata:
  name: repository
  namespace: alfresco
  labels:
    app: alfresco
    tiers: engine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alfresco
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: alfresco
        tiers: engine
    spec:
      containers:
      - image: fjudith/alfresco:repository
        name: alfresco
        env: 
        - name: ALFRESCO_HOSTNAME
          value: docs.example.com
        - name: ALFRESCO_PROTOCOL
          value: http
        - name: ALFRESCO_PORT
          value: "8080"
        - name: SHARE_HOSTNAME
          value: docs.example.com
        - name: SHARE_PROTOCOL
          value: http
        - name: SHARE_PORT
          value: "8080"
        - name: DB_KIND
          value: postgresql
        - name: DB_HOST
          value: postgres
        - name: DB_NAME
          value: alfresco
        - name: DB_USERNAME
          value: alfresco
        # $ kubectl create secret generic postgres-pass --from-file=alfresco.postgres.password.txt
        # make sure postgres.password.txt does not have a trailing newline
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: alfresco-pass
              key: alfresco.postgres.password.txt
        - name: OOO_ENABLED
          value: "true"
        - name: OOO_HOSTNAME
          value: "libreoffice"
        - name: OOO_PORT
          value: "8100"
        - name: SOLR_INDEX_SUBSYSTEM
          value: "solr6"
        - name: SOLR_HOST
          value: "search"
        - name: SOLR_PORT
          value: "8983"
        ports:
        - containerPort: 137
          name: netbios-ns
        - containerPort: 138
          name: netbios-dgm
        - containerPort: 139
          name: netbios-ssn
        - containerPort: 21
          name: ftp
        - containerPort: 445
          name: microsoft-ds
        - containerPort: 8080
          name: http-proxy
        volumeMounts:
        - name: alfresco-data
          mountPath: /var/lib/alfresco/alf_data
          subPath: data
        - name: alfresco-data
          mountPath: /usr/share/tomcat/logs
          subPath: log
        livenessProbe:
          tcpSocket:
              port: 8080
          initialDelaySeconds: 60
          timeoutSeconds: 5
        readinessProbe:
          tcpSocket:
            port: 8080
          timeoutSeconds: 5
      initContainers:
      - name: init-postgres
        image: busybox
        command: ['sh', '-c', 'until nc -zv -w 5 postgres 5432; do echo waiting for postgres; sleep 2; done;']
      volumes:
      - name: alfresco-data
        persistentVolumeClaim:
          claimName: alfresco-data
---