apiVersion: v1
kind: Service
metadata:
  name: share
  namespace: alfresco
  labels:
    app: alfresco
    tiers: frontend
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: alfresco
    tiers: frontend
---